### ISSUE TITLE
Suggestion: We need a model for subscriptions

### ISSUE THREAD

**Issue by alsami** [NubCoda/MEAN-Board#5]
A user should be able to subscribe a whole category or thread to receive it's latest posts in his usercontrol panel.

**Comment by lxkrmr** [comment]
I added two new properties to the User Model:
- subscribed_categories and
- subscribed_threads

Both are Arrays that store Ref-Ids for Category / Thread Objects. This IDs will be populate if
- the user logged in and
- the user is updated

Please use the update Method to add a new subscription

FYI:
- First I trief to store both usbcriptions in one Object, but I got some trouble during population, so I splittedt it into two properties
- for updating a user pls use /user/byID/<userID> for the route. I had to change it because of login and logout

Pls reopen if you need depper population or something else

**Comment by lxkrmr** [comment]
if you want to cherry pick you can use this commit
https://github.com/NubCoda/MEAN-Board/commit/19768a87dcf3709de136131ceba5927bd40fb41d
